name: GeneralStore

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Start Android Emulator and run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-window -no-audio -no-boot-anim
          disable-animations: false
          emulator-boot-timeout: 600
          script: |
            echo "Start emulator readiness checks"
            adb wait-for-device
            adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
            sleep 30

            echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
            echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
            echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV

            echo "Install Appium + driver"
            npm install -g wait-on
            npx appium driver install uiautomator2

            echo "Start Appium server"
            nohup npx appium --base-path /wd/hub --session-override --relaxed-security > appium.log 2>&1 &
            npx wait-on tcp:4723

            echo "Restore dotnet dependencies"
            dotnet restore

            echo "Build project"
            dotnet build --configuration Release

            echo "Wait for emulator"
            adb wait-for-device && sleep 60


            echo "Run NUnit tests"
             dotnet test ./GeneralStore/GeneralStore.sln --configuration Release --logger:"trx;LogFileName=test_results.trx" -- TestRunParameters.Parameter(name=\"uiautomator2ServerLaunchTimeout\", value=\"90000\")
      - name: Upload Appium logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-log
          path: appium.log

      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: NUnit Tests
          path: "**/TestResults/*.trx"
          reporter: dotnet-trx
