name: GeneralStore

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install Java (for Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-window -no-audio -no-boot-anim
          script: echo "Emulator booted"

      - name: Start Appium server
        run: |
          npm install -g appium
          appium --log-level info &
          sleep 10

      - name: Restore dotnet dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run NUnit tests
        run: dotnet test --configuration Release --logger:"trx;LogFileName=test_results.trx"

      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: NUnit Tests
          path: "**/TestResults/*.trx"
          reporter: dotnet-trx
