name: GeneralStore

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install Java (for Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Appium
        run: npm install -g appium

      - name: Install emulator dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpulse0 libglu1

      - name: Start Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-snapshot -noaudio -no-boot-anim -gpu swiftshader_indirect
          script: |
            adb wait-for-device
            adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 5; done'
            echo "Emulator booted"

      - name: Start Appium server
        run: appium --log-level info &
      
      - name: Restore dotnet dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run NUnit tests
        run: dotnet test --configuration Release --logger:"trx;LogFileName=test_results.trx"

      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: NUnit Tests
          path: "**/TestResults/*.trx"
          reporter: dotnet-trx
