name: GeneralStore
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  android-tests:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
 
      - name: Install Java (for Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
 
      - name: Setup Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel_5
          script: |
            echo "Start Appium server"
            npm install -g appium
            appium --log-level info &
 
            echo "Restore dotnet dependencies"
            dotnet restore
 
            echo "Build project"
            dotnet build --configuration Release
 
            echo "Run NUnit tests"
            dotnet test --configuration Release --logger:"trx;LogFileName=test_results.trx"
 
      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: NUnit Tests
          path: "**/TestResults/*.trx"
          reporter: dotnet-trx